version: '3.9'

services:
  db:
    image: postgres
    container_name: postgres_db
    restart: always
    ports:
      - '5532:5432'
    environment:
      POSTGRES_PASSWORD: pass123
  test-db:
    image: postgres
    restart: always
    ports: 
      - "5533:5432"
    environment:
      POSTGRES_PASSWORD: pass123
